DROP TABLE IF EXISTS `#__gw_banners`;

CREATE TABLE `#__gw_banners` (
	`id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`filename` VARCHAR(25) NOT NULL,
	`feature` TINYINT(1),
	PRIMARY KEY(`id`)
) ENGINE=MyISAM AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;