<?php
if( !defined( '_JEXEC' )) die( 'Direct Access to '.basename(__FILE__).' is not allowed.' ); 

$templates = array();
$templates['basic'] = array(
                           'fromSiteID' => ':master_db:',
                           'groupName' => 'basic_package',
                           'sku' => '',
                           'title' => 'Git Basic',
                           'description' => '',
                           'validity' => '1',
                           'validity_unit' => 'days',
                           'maxsite' => '0',
                           'expireurl' => 'http://www.gitwitty.com/renewal.php',
                           'toDomains' => array( 'http://{site_url}/multisites/{site_alias}'),
                           'toSiteID' => 'u{user_id}{site_prefix}',
                           'shareDB' => '',
                           'adminUserID' => '64',
                           'toDBHost' => 'localhost',
                           'toDBName' => 'gitwitty_{site_id}',
                           'toDBUser' => 'gitwitty',
                           'toDBPsw' => 'p!p@cw!tty',
                           'toPrefix' => '{site_id}_',
                           'deploy_create' => 'on',
                           'toFTP_enable' => '1',
                           'toFTP_host' => 'ftp.gitwitty.com',
                           'toFTP_port' => '21',
                           'toFTP_user' => '{site_id}',
                           'toFTP_psw' => '{site_id}123',
                           'toFTP_rootpath' => '/home/gitwitty/public_html/multisites/{site_alias}',
                           'symboliclinks' => array( 'administrator' => array( 'action' => 'SL'),
                                'cache' => array( 'action' => 'mkdir', 'readOnly' => '1'),
                                'cgi-bin' => array( 'action' => 'SL'),
                                'components' => array( 'action' => 'SL'),
                                'images' => array( 'action' => 'special'),
                                'includes' => array( 'action' => 'SL'),
                                'installation' => array( 'action' => 'dirlinks'),
                                'language' => array( 'action' => 'SL'),
                                'libraries' => array( 'action' => 'SL'),
                                'logs' => array( 'action' => 'mkdir', 'readOnly' => '1'),
                                'media' => array( 'action' => 'SL'),
                                'modules' => array( 'action' => 'SL'),
                                'multisites' => array( 'action' => 'SL'),
                                'plugins' => array( 'action' => 'SL'),
                                'templates' => array( 'action' => 'special'),
                                'tmp' => array( 'action' => 'mkdir', 'readOnly' => '1'),
                                'xmlrpc' => array( 'action' => 'SL'),
                                '.ftpquota' => array( 'action' => 'SL'),
                                'htaccess.txt' => array( 'action' => 'SL'),
                                'robots.txt' => array( 'action' => 'SL'),
                                'index.php' => array( 'action' => 'redirect', 'readOnly' => '1'),
                                'index2.php' => array( 'action' => 'redirect', 'readOnly' => '1')),
                           'dbsharing' => array( 'dbsh_UserSharing' => 'none'));
$templates['pro'] = array(
                           'fromSiteID' => ':master_db:',
                           'groupName' => 'pro_package',
                           'sku' => '',
                           'title' => 'Git Pro',
                           'description' => '',
                           'validity' => '1',
                           'validity_unit' => 'days',
                           'maxsite' => '0',
                           'expireurl' => 'http://www.gitwitty.com/renewal.php',
                           'toDomains' => array( 'http://{site_url}/multisites/{site_alias}'),
                           'toSiteID' => 'u{user_id}{site_prefix}',
                           'shareDB' => '',
                           'adminUserID' => '64',
                           'toDBHost' => 'localhost',
                           'toDBName' => 'gitwitty_{site_id}',
                           'toDBUser' => 'gitwitty_dbadmin',
                           'toDBPsw' => 'db@dm1n',
                           'toPrefix' => '{site_id}_',
                           'deploy_create' => 'on',
                           'toFTP_enable' => '0',
                           'toFTP_host' => 'ftp.gitwitty.com',
                           'toFTP_port' => '21',
                           'toFTP_user' => '{site_id}',
                           'toFTP_psw' => '{site_id}123',
                           'toFTP_rootpath' => '/home/gitwitty/public_html/multisites/{site_alias}',
                           'symboliclinks' => array( 'administrator' => array( 'action' => 'SL'),
                                'cache' => array( 'action' => 'mkdir', 'readOnly' => '1'),
                                'cgi-bin' => array( 'action' => 'SL'),
                                'components' => array( 'action' => 'ignore'),
                                'images' => array( 'action' => 'special'),
                                'includes' => array( 'action' => 'SL'),
                                'installation' => array( 'action' => 'dirlinks'),
                                'language' => array( 'action' => 'SL'),
                                'libraries' => array( 'action' => 'SL'),
                                'logs' => array( 'action' => 'mkdir', 'readOnly' => '1'),
                                'media' => array( 'action' => 'SL'),
                                'modules' => array( 'action' => 'SL'),
                                'multisites' => array( 'action' => 'ignore'),
                                'plugins' => array( 'action' => 'ignore'),
                                'templates' => array( 'action' => 'special'),
                                'tmp' => array( 'action' => 'mkdir', 'readOnly' => '1'),
                                'xmlrpc' => array( 'action' => 'SL'),
                                '.ftpquota' => array( 'action' => 'SL'),
                                '.htaccess' => array( 'action' => 'SL'),
                                'htaccess.txt' => array( 'action' => 'SL'),
                                'robots.txt' => array( 'action' => 'SL'),
                                'index.php' => array( 'action' => 'redirect', 'readOnly' => '1'),
                                'index2.php' => array( 'action' => 'redirect', 'readOnly' => '1')),
                           'dbsharing' => array( 'dbsh_UserSharing' => 'none'));
